analyzer:
  errors:
    unused_import: warning
    dead_code: warning
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - unnecessary_null_checks
    - prefer_final_fields
    - avoid_empty_else
    - prefer_single_quotes
    - prefer_interpolation_to_compose_strings
    - sort_child_properties_last
