name: beged
version: 1.0.0+1
description: A fun and user-friendly marketplace app to connect buyers and sellers.

environment:
  sdk: ">=2.17.0 <3.0.0"

# Platform support
platforms:
  android:
  ios:
  web:

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  provider: ^6.1.2
  cached_network_image: ^3.4.1

  # Animations & Theme
  flutter_animate: ^4.5.2
  flex_color_scheme: ^7.0.0
  multi_select_flutter: ^4.1.3
  flutter_staggered_grid_view: ^0.7.0
  step_progress_indicator: ^1.0.2

  # Table viewer
  data_table_2: ^2.5.18

  # Image upload and handling
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  flutter_image_compress: ^2.4.0

  # Networking
  dio: ^5.1.0
  http: ^1.1.0

  # Firebase (if needed for authentication or analytics)
  firebase_core: ^3.13.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  google_generative_ai: ^0.4.6
  firebase_ai: ^2.0.0
  
  # Communication
  url_launcher: ^6.3.1
  firebase_app_check: ^0.3.2+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#673AB7"
    theme_color: "#673AB7"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#673AB7"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/items_metadata_lists.json
    - assets/master_tags.json
    - assets/privacy_policy.txt
    - assets/terms_and_conditions.txt
    - lib/l10n/

    - assets/images/all.png
    - assets/images/app_icon.png
    - assets/images/app_icon_foreground.png
