// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCteSy1aRX4rEqtsjAyEKv0oH6i5SeNfBE',
    appId: '1:46669496533:web:2e423d05750b7a31a2625c',
    messagingSenderId: '46669496533',
    projectId: 'eco-closet-f0942',
    authDomain: 'eco-closet-f0942.firebaseapp.com',
    storageBucket: 'eco-closet-f0942.firebasestorage.app',
    measurementId: 'G-70FQV5BH22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA7hIJGBrRXLJog-UV-mjB_yV_Uf3JrnQ',
    appId: '1:46669496533:android:76f045c2c9f95c6fa2625c',
    messagingSenderId: '46669496533',
    projectId: 'eco-closet-f0942',
    storageBucket: 'eco-closet-f0942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFq76ukIh7HgIgDSnvN8aVWTvt7n6aBUk',
    appId: '1:46669496533:ios:351e69c85338b5cba2625c',
    messagingSenderId: '46669496533',
    projectId: 'eco-closet-f0942',
    storageBucket: 'eco-closet-f0942.firebasestorage.app',
    iosBundleId: 'com.example.ecoCloset',
  );
}
